Repository kaushallalani/MusicMate, pull requests merged in 2024-06, with the labels that each got.

#1 Designed the songsplaylist screen and songplay screen.
  lib/components/newBox.dart
  lib/models/playlistProvider.dart
  lib/pages/home/index.dart
  lib/pages/songsPage/index.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: Initial

#2 Added Login Screen
  .gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/kotlin/com/example/demo/MainActivity.kt
  android/build.gradle
  assets/images/google.png
  lib/components/myDrawer.dart
  lib/components/snackbar.dart
  lib/main.dart
  lib/pages/login/index.dart
  lib/services/authentication.dart
  lib/themes/metrics.dart
  linux/CMakeLists.txt
  pubspec.yaml
Labels: enhancement

#3 Added Navigation and Constants Modules
  README.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  assets/images/library.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/components/bottomNav/custom_bottom_navigation.dart
  lib/components/bottomNav/custom_bottom_navigation_bar_item.dart
  lib/components/button/button_component.dart
  lib/components/button/index.dart
  lib/components/button/styles.dart
  lib/components/icon/icon_component.dart
  lib/components/icon/index.dart
  lib/components/icon/styles.dart
  lib/components/index.dart
  lib/components/myDrawer.dart
  lib/components/newBox.dart
  lib/components/text/index.dart
  lib/components/text/styles.dart
  lib/components/text/text_component.dart
  lib/constants/colors.dart
  lib/constants/fonts.dart
  lib/constants/i18n/strings.g.dart
  lib/constants/i18n/strings.i18n.json
  lib/constants/i18n/strings_ar.i18n.json
  lib/constants/images.dart
  lib/constants/metrics.dart
  lib/constants/theme.dart
  lib/main.dart
  lib/models/playlistProvider.dart
  lib/navigation/app_navigation.dart
  lib/navigation/navigation.dart
  lib/pages/dashboard/index.dart
  lib/pages/home/index.dart
  lib/pages/library/index.dart
  lib/pages/library/styles.dart
  lib/pages/login/index.dart
  lib/pages/search/index.dart
  lib/pages/search/styles.dart
  lib/pages/settings/index.dart
  lib/pages/songsPage/index.dart
  lib/services/authentication.dart
  lib/themes/theme_provider.dart
  linux/CMakeLists.txt
  linux/my_application.cc
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
  web/index.html
  web/manifest.json
  windows/CMakeLists.txt
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
  windows/runner/Runner.rc
  windows/runner/main.cpp
Labels: enhancement

#4 Changed Firebase Configuration
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  android/settings.gradle
  firebase.json
  lib/components/myDrawer.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/pages/home/index.dart
  lib/pages/login/index.dart
  lib/services/authentication.dart
Labels: documentation

#5 Added Bloc Setup
  devtools_options.yaml
  lib/components/CustomSongTile/custom_song_tile.dart
  lib/components/footer/footer_component.dart
  lib/components/footer/styles.dart
  lib/components/index.dart
  lib/components/text/text_component.dart
  lib/main.dart
  lib/models/user.dart
  lib/navigation/app_navigation.dart
  lib/pages/authentication/bloc/authentication_bloc.dart
  lib/pages/authentication/bloc/authentication_event.dart
  lib/pages/authentication/bloc/authentication_state.dart
  lib/pages/dashboard/bloc/dashboard_bloc.dart
  lib/pages/dashboard/bloc/dashboard_event.dart
  lib/pages/dashboard/bloc/dashboard_state.dart
  lib/pages/home/index.dart
  lib/pages/login/index.dart
  lib/pages/splash/index.dart
  lib/services/auth.dart
  lib/services/firestoreService.dart
  lib/themes/metrics.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#6 Feature/login
  lib/models/user.dart
  lib/navigation/app_navigation.dart
  lib/pages/authentication/bloc/authentication_bloc.dart
  lib/pages/authentication/bloc/authentication_event.dart
  lib/pages/login/index.dart
  lib/pages/splash/index.dart
  lib/services/auth.dart
  lib/services/authentication.dart
Labels: bug, enhancement

#7 Added Dependency injection and fixed bloc flow.
  lib/components/myDrawer.dart
  lib/components/newBox.dart
  lib/extra/auth.dart
  lib/extra/authentication.dart
  lib/injectionContainer/injection_container.dart
  lib/main.dart
  lib/models/user.dart
  lib/models/user.g.dart
  lib/pages/authentication/bloc/authentication_bloc.dart
  lib/pages/authentication/bloc/authentication_state.dart
  lib/pages/dashboard/bloc/dashboard_bloc.dart
  lib/pages/dashboard/bloc/dashboard_event.dart
  lib/pages/dashboard/bloc/dashboard_state.dart
  lib/pages/dashboard/index.dart
  lib/pages/home/index.dart
  lib/pages/login/index.dart
  lib/pages/settings/index.dart
  lib/repositories/firebase_repository.dart
  lib/repositories/firebase_repository_impl.dart
  lib/repositories/user_repository.dart
  lib/services/firebase_service.dart
  lib/services/firestoreService.dart
  lib/themes/theme_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#9 Added Single Device Login Feature
  lib/models/fieldvalue_converter.dart
  lib/models/user.dart
  lib/models/user.g.dart
  lib/pages/dashboard/index.dart
  lib/repositories/auth_repository_impl.dart
  lib/services/auth_service.dart
Labels: enhancement

#10 Added session management flow
  analysis_options.yaml
  android/app/src/main/AndroidManifest.xml
  android/gradle/wrapper/gradle-wrapper.properties
  lib/bloc/authentication/authentication_bloc.dart
  lib/bloc/authentication/authentication_event.dart
  lib/bloc/authentication/authentication_state.dart
  lib/bloc/dashboard/dashboard_bloc.dart
  lib/bloc/dashboard/dashboard_event.dart
  lib/bloc/dashboard/dashboard_state.dart
  lib/bloc/session/session_bloc.dart
  lib/bloc/session/session_event.dart
  lib/bloc/session/session_state.dart
  lib/components/button/styles.dart
  lib/components/footer/footer_component.dart
  lib/components/index.dart
  lib/components/myDrawer.dart
  lib/components/textFormField/styles.dart
  lib/components/textFormField/text_form_field_component.dart
  lib/extra/authentication.dart
  lib/injectionContainer/injection_container.dart
  lib/main.dart
  lib/models/session.dart
  lib/models/session.g.dart
  lib/models/user.dart
  lib/navigation/app_navigation.dart
  lib/navigation/navigation.dart
  lib/pages/dashboard/bloc/dashboard_bloc.dart
  lib/pages/dashboard/bloc/dashboard_event.dart
  lib/pages/dashboard/bloc/dashboard_state.dart
  lib/pages/dashboard/index.dart
  lib/pages/home/index.dart
  lib/pages/listenTogether/index.dart
  lib/pages/listenTogether/styles.dart
  lib/pages/login/index.dart
  lib/pages/session/index.dart
  lib/pages/settings/index.dart
  lib/pages/signup/index.dart
  lib/repositories/auth_repository_impl.dart
  lib/repositories/dashboard_repository.dart
  lib/repositories/dashboard_repository_impl.dart
  lib/repositories/user_repository.dart
  lib/services/auth_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#11 Login and Signup screen design
  assets/images/back_arrow.png
  assets/images/icon.png
  lib/constants/regex.dart
  lib/constants/theme.dart
  lib/pages/login/index.dart
  lib/pages/session/index.dart
  lib/pages/signup/index.dart
Labels: Design

#12 Added custom colors
  lib/constants/custom_colors.dart
  lib/constants/theme.dart
  lib/main.dart
  lib/pages/login/index.dart
  lib/pages/signup/index.dart
Labels: enhancement
